class Const():
    abnormality_list = [
    'inflammation',
    'reduced vascularity',
    'angioectasia',
    'erosion',
    'polyp',
    'pseudopolyp',
    'edema',
    'fibrin',
    'biopsy lesion',
    'lipoma',
    'hemorrhoid'
]

    category_dict = [
    {'name':'normal',
     'id':0,
     'abnormalities':['normal']},
    {'name':'inflammation',
     'id':1,
     'abnormalities':[
        'inflammation',
        'reduced vascularity',
        'fibrin',
        'erosion',
        'edema'
        ]},
    {'name':'polyp',
     'id':2,
     'abnormalities':[
        'polyp',
        'pseudopolyp'
        ]},
    {'name':'hemorrhoid',
     'id':3,
     'abnormalities': ['hemorrhoid']},
    {'name':'biopsy lesion',
     'id':4,
     'abnormalities': ['biopsy lesion']},
    {'name':'angioectasia',
     'id':5,
     'abnormalities': ['angioectasia']},
    {'name':'lipoma',
     'id':6,
     'abnormalities': ['lipoma']},
]
   
    classes = ['pseudopolyp', 
               'biopsy lesion', 
               'inflammation, reduced vascularity, pseudopolyp, edema, fibrin', 
               'reduced vascularity, erosion, edema', 
               'normal', 
               'inflammation, reduced vascularity, edema, fibrin', 
               'inflammation, fibrin', 
               'polyp', 
               'inflammation, erosion, fibrin', 
               'reduced vascularity, edema', 
               'angioectasia', 
               'reduced vascularity, edema, fibrin', 
               'inflammation, erosion', 
               'inflammation, reduced vascularity, edema', 
               'hemorrhoid', 
               'inflammation', 
               'erosion', 
               'inflammation, bleeding', 
               'lipoma', 
               'reduced vascularity', 
               'edema', 
               'reduced vascularity, erosion, fibrin', 
               'inflammation, reduced vascularity, fibrin', 
               'reduced vascularity, erosion, edema, fibrin', 
               'edema, fibrin', 
               'inflammation, reduced vascularity, erosion, fibrin', 
               'inflammation, reduced vascularity', 
               'inflammation, reduced vascularity, erosion']
    test_classes = ['pseudopolyp', 
                   'biopsy lesion', 
                   'inflammation, reduced vascularity, pseudopolyp, edema, fibrin', 
                   'reduced vascularity, erosion, edema', 
                   'normal', 
                   'inflammation, reduced vascularity, edema, fibrin', 
                   'inflammation, fibrin', 
                   'polyp', 
                   'inflammation, erosion, fibrin', 
                   'reduced vascularity, edema', 
                   'angioectasia', 
                   'reduced vascularity, edema, fibrin', 
                   'inflammation, erosion', 
                   'inflammation, reduced vascularity, edema', 
                   'hemorrhoid', 
                   'inflammation', 
                   'erosion', 
                   'inflammation, bleeding', 
                   'lipoma', 
                   'reduced vascularity', 
                   'edema']